apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubesnap.fullname" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubesnap.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "kubesnap.serviceAccount" . }}
    namespace: {{ .Release.Namespace }}
