apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubesnap.fullname" . }}
  namespace: {{ include "kubesnap.namespace" . }}
  labels:
{{ include "kubesnap.labels" . | indent 4 }}
  annotations:
{{ include "kubesnap.annotations" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
{{ include "kubesnap.annotations" . | indent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{include "kubesnap.serviceAccount" .}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.image.repository }}
          tag: {{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--metrics-bind-address=:{{ .Values.service.metrics.port }}"
            - "--health-probe-bind-address=:{{ .Values.service.health.port }}"
            - "--metrics-secure={{ .Values.service.metrics.secure }}"
            - "--batch-cleanup-interval={{ .Values.cleanup.interval }}"
            {{- if  .Values.service.metrics.secure }}
            - "--metrics-cert-path=/etc/metrics-certs"
            - "--metrics-cert-name={{ .Values.service.metrics.cert.Name }}"
            - "--metrics-cert-key={{ .Values.service.metrics.cert.Key }}"
            {{- end}}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.metrics.port }}
            - name: health
              containerPort: {{ .Values.service.health.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
          {{- if  .Values.service.metrics.secure  }}
            - name: metrics-certs
              mountPath: /etc/metrics-certs
              readOnly: true
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "kubesnap.fullname" . }}-config
        {{- if  .Values.service.metrics.secure  }}
        - name: metrics-certs
          secret:
            secretName: {{ .Values.service.metrics.cert.SecretName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}