name: Release Image & Helm Chart

on:
  push:
    tags:
      - "v*.*.*"  # Triggers on tags like v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    env:
      IMAGE_NAME: ghcr.io/infrautils/kubeclean
      CHART_NAME: kubeclean

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Release Version
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Container Image
        run: |
          docker build -t "${IMAGE_NAME}:${VERSION}" .
          docker push "${IMAGE_NAME}:${VERSION}"

      - name: Update image.tag in values.yaml
        run: |
          sed -i "s|^\( *tag:\).*|\1 \"${VERSION}\"|" ./chart/values.yaml

      - name: Update version & appVersion in Chart.yaml
        run: |
          sed -i "s/^version:.*/version: ${VERSION}/" ./chart/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${VERSION}\"/" ./chart/Chart.yaml

      - name: Package Helm Chart
        run: |
          helm dependency update ./chart
          helm lint ./chart
          helm package ./chart --version "${VERSION}" --app-version "${VERSION}"

      - name: Push Helm Chart to OCI Registry
        run: |
          helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          helm push ./${CHART_NAME}-${VERSION}.tgz oci://ghcr.io/infrautils/charts

      - name: Generate Release Notes
        run: |
          cat <<EOF > release-notes.md
          ## 🚀 Release Details for \`${VERSION}\`

          | Component         | Version |
          |------------------|---------|
          | Container Image   | \`${IMAGE_NAME}:${VERSION}\` |
          | Helm Chart Version| \`${VERSION}\` |
          | App Version       | \`${VERSION}\` |

          ### ✅ Changes:
          - See commit history: https://github.com/infrautils/kubeclean/commits/${VERSION}

          ### ✅ Helm Install:
          \`\`\`bash
          helm registry login ghcr.io
          helm pull oci://ghcr.io/infrautils/charts/kubeclean --version ${VERSION}
          \`\`\`

          EOF

      - name: Create GitHub Release (Attach Helm Chart)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ github.ref }}"
          body_path: release-notes.md
          files: |
            ./${CHART_NAME}-${VERSION}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
